name: highlighter
description: Syntax highlighting for Dart with lots of languages and themes support.
version: 0.1.0+1
homepage: https://github.com/Purple-Graphite/highlight

dependencies:
  collection: ^1.15.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
  path: ^1.8.0
