name: highlight
description: Syntax highlighting for Dart with lots of languages and themes support.
version: 0.7.0
homepage: https://github.com/Purple-Graphite/highlight/tree/master/highlight
publish_to: 'none'

dependencies:
  collection: ^1.15.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
  path: ^1.8.0
